services:
  app:
    # image: dbacr2026.azurecr.io/gotham-harbor-app:latest
    # platform: linux/amd64   # this runs the ACR image in Rosetta emulation mode for mac's arm64/v8

    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: app
    working_dir: /workspace

    volumes:
      - .:/workspace:cached
      - /opt/venv
      - ./_data:/data
      - ./_lake:/lake
      # - ~/.azure:/home/developer/.azure  # Mount Azure CLI credentials
      # - ~/.azure:/root/.azure             # Fallback if running as root

    env_file:
      - .env

    environment:
      - PYTHONUNBUFFERED=1


    # Keep container alive for Dev Containers to attach reliably
    command: sleep infinity
    # command: bash -lc "source /opt/venv/bin/activate && python src/main.py; sleep infinity"


volumes:
  venv:
  uvcache:
